[package]
name = "fractals"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.23.2"
glam = { version = "0.27.0", features = ["fast-math", "bytemuck"] }
iced = { version = "0.12.1", features = ["image", "advanced"] }

[lints.clippy]
needless_return = "allow"
